name: rehber_fleet_app
description: Şirket içi araç takip (Kiralama/İade/Rezervasyon) — Rehber Otomotiv
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  pdf: ^3.10.8
  printing: ^5.13.4
  excel: ^4.0.3
  uuid: ^4.4.2
  path_provider: ^2.1.3
file_picker: ^8.0.3
  share_plus: ^10.0.2
  mailer: ^6.1.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
